backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "news"
    label: "Новости"
    folder: "content/news"
    create: true
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Текст", name: "body", widget: "markdown" }