backend:
  name: github
  repo: platstarinum-prog/lizei167
  branch: main

site_url: https://lizei167.netlify.app
media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "news"
    label: "Новости"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Текст", name: "body", widget: "markdown" }
